
// Images (put your images in src/assets/images/)
import hero1 from "../assets/images/hero1.jpg"
import hero2 from "../assets/images/hero2.jpg"
import hero3 from "../assets/images/hero3.jpg"

// export const vendors = [
//   {
//     id: 1,
//     name: "Mama Put Kitchen",
//     banner: "/images/food1.jpg",
//     logo: "/images/profile1.jpg",
//     category: "Local dishes",
//     rating: 4.5,
//   },
//   {
//     id: 2,
//     name: "Chicken Republic",
//     banner: "/images/food3.jpg",
//     logo: "/images/profile2.jpg",
//     category: "Fast food",
//     rating: 4.3,
//   },
//   {
//     id: 3,
//     name: "Chicken Republic",
//     banner: "/images/food2.jpg",
//     logo: "/images/profile2.jpg",
//     category: "Fast food",
//     rating: 4.3,
//   },
//  {
//     id: 3,
//     name: "Chicken Republic",
//     banner: "/images/food4.jpg",
//     logo: "/images/profile2.jpg",
//     category: "Fast food",
//     rating: 4.3,
//   },{
//     id: 3,
//     name: "Chicken Republic",
//     banner: "/images/food5.jpg",
//     logo: "/images/profile2.jpg",
//     category: "Fast food",
//     rating: 4.3,
//   },{
//     id: 3,
//     name: "Chicken Republic",
//     banner: "/images/food6.jpg",
//     logo: "/images/profile2.jpg",
//     category: "Fast food",
//     rating: 4.3,
//   },

// ];


export const banners = [
  {
   image: hero1,
   title: "Big Deals Every Day 🔥",
   desc: "Shop discounted products from trusted vendors",
  },
  {
   image: hero2,
   title: "AI Shopping Assistant 🤖",
   desc: "Find products instantly with smart search",
  },
  {
   image: hero3,
   title: "Trusted Vendors 🏪",
   desc: "Buy directly from verified sellers",
  },
 ]



 export const products = [
  {
    id: 1,
    name: 'Premium Wireless Headphones',
    price: 199.99,
    originalPrice: 299.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
    category: 'Electronics',
    rating: 4.5,
    reviews: 234,
    seller: 'TechStore Pro',
    sellerId: 1,
    discount: 33,
    description:
      'High-quality wireless headphones with noise cancellation, 30-hour battery life, and premium comfort.',
    specs: [
      { label: 'Bluetooth Version', value: '5.0' },
      { label: 'Battery Life', value: '30 hours' },
      { label: 'Weight', value: '250g' },
      { label: 'Color Options', value: 'Black, Silver, Gold' },
    ],
  },
  {
    id: 2,
    name: 'Smart Watch Ultra',
    price: 299.99,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop',
    category: 'Electronics',
    rating: 4.8,
    reviews: 567,
    seller: 'SmartTech',
    sellerId: 2,
    discount: 0,
    description:
      'Advanced smartwatch with health monitoring, GPS tracking, and 7-day battery life.',
    specs: [
      { label: 'Display', value: 'AMOLED 1.4"' },
      { label: 'Battery', value: '7 days' },
      { label: 'Water Resistance', value: '5ATM' },
      { label: 'Health Tracking', value: 'Full' },
    ],
  },
  {
    id: 3,
    name: 'Ultra HD Camera',
    price: 1299.99,
    originalPrice: 1599.99,
    image: 'https://images.unsplash.com/photo-1611532736579-6b16e2b50449?w=500&h=500&fit=crop',
    category: 'Electronics',
    rating: 4.7,
    reviews: 189,
    seller: 'CameraWorld',
    sellerId: 3,
    discount: 19,
    description:
      'Professional-grade 4K camera with RAW shooting capability and advanced autofocus.',
    specs: [
      { label: 'Resolution', value: '24MP' },
      { label: 'Video', value: '4K@60fps' },
      { label: 'Lens Mount', value: 'RF' },
      { label: 'ISO Range', value: '100-25600' },
    ],
  },
  {
    id: 4,
    name: 'Portable Speaker',
    price: 79.99,
    originalPrice: 129.99,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&h=500&fit=crop',
    category: 'Electronics',
    rating: 4.3,
    reviews: 445,
    seller: 'AudioPro',
    sellerId: 1,
    discount: 38,
    description: 'Waterproof bluetooth speaker with 12-hour battery and 360° sound.',
    specs: [
      { label: 'Power', value: '20W' },
      { label: 'Battery', value: '12 hours' },
      { label: 'Water Rating', value: 'IPX7' },
      { label: 'Range', value: '30m' },
    ],
  },
  {
    id: 5,
    name: 'Gaming Laptop Pro',
    price: 1499.99,
    originalPrice: 1999.99,
    image: 'https://images.unsplash.com/photo-1588872657840-11f894fe8590?w=500&h=500&fit=crop',
    category: 'Computers',
    rating: 4.6,
    reviews: 312,
    seller: 'TechStore Pro',
    sellerId: 1,
    discount: 25,
    description: 'High-performance gaming laptop with RTX 4080 and 144Hz display.',
    specs: [
      { label: 'GPU', value: 'RTX 4080' },
      { label: 'CPU', value: 'Intel i9' },
      { label: 'RAM', value: '32GB' },
      { label: 'Display', value: '16" 144Hz' },
    ],
  },
  {
    id: 6,
    name: 'Mechanical Keyboard',
    price: 149.99,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1587829191301-e8500b1d1d08?w=500&h=500&fit=crop',
    category: 'Accessories',
    rating: 4.9,
    reviews: 623,
    seller: 'GearHub',
    sellerId: 4,
    discount: 0,
    description: 'Premium mechanical keyboard with RGB lighting and hot-swappable switches.',
    specs: [
      { label: 'Switch Type', value: 'Mechanical' },
      { label: 'Layout', value: '104 Keys' },
      { label: 'Lighting', value: 'RGB' },
      { label: 'Connection', value: 'Wireless' },
    ],
  },
  {
    id: 7,
    name: 'Premium Mouse',
    price: 99.99,
    originalPrice: 159.99,
    image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=500&h=500&fit=crop',
    category: 'Accessories',
    rating: 4.4,
    reviews: 534,
    seller: 'GearHub',
    sellerId: 4,
    discount: 38,
    description: 'Ergonomic gaming mouse with 16k DPI sensor and programmable buttons.',
    specs: [
      { label: 'DPI', value: 'Up to 16000' },
      { label: 'Buttons', value: '8 Programmable' },
      { label: 'Weight', value: '80g' },
      { label: 'Battery', value: '70 hours' },
    ],
  },
  {
    id: 8,
    name: 'Monitor 4K 144Hz',
    price: 599.99,
    originalPrice: 799.99,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&h=500&fit=crop',
    category: 'Electronics',
    rating: 4.7,
    reviews: 287,
    seller: 'DisplayPro',
    sellerId: 5,
    discount: 25,
    description: '27" 4K gaming monitor with 144Hz refresh rate and HDR support.',
    specs: [
      { label: 'Resolution', value: '4K (3840x2160)' },
      { label: 'Refresh Rate', value: '144Hz' },
      { label: 'Panel Type', value: 'IPS' },
      { label: 'HDR', value: 'HDR10' },
    ],
  },
]

export const vendors = [
  {
    id: 1,
    name: 'TechStore Pro',
    avatar: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=200&h=200&fit=crop',
    category: 'Electronics',
    rating: 4.7,
    products: 2345,
    followers: 45000,
    verified: true,
    description: 'Leading electronics retailer with quality products and fast shipping.',
  },
  {
    id: 2,
    name: 'SmartTech',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    category: 'Wearables',
    rating: 4.8,
    products: 1200,
    followers: 32000,
    verified: true,
    description: 'Specialized in smart devices and wearable technology.',
  },
  {
    id: 3,
    name: 'CameraWorld',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    category: 'Photography',
    rating: 4.6,
    products: 567,
    followers: 28000,
    verified: true,
    description: 'Premium cameras and photography equipment for professionals.',
  },
  {
    id: 4,
    name: 'GearHub',
    avatar: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=200&h=200&fit=crop',
    category: 'Gaming',
    rating: 4.9,
    products: 890,
    followers: 52000,
    verified: true,
    description: 'Ultimate destination for gaming peripherals and accessories.',
  },
  {
    id: 5,
    name: 'DisplayPro',
    avatar: 'https://images.unsplash.com/photo-1507842217343-583f20270319?w=200&h=200&fit=crop',
    category: 'Displays',
    rating: 4.5,
    products: 445,
    followers: 18000,
    verified: true,
    description: 'High-quality monitors and display solutions.',
  },
]

export const categories = [
  { id: 1, name: 'Electronics', icon: '📱' },
  { id: 2, name: 'Computers', icon: '💻' },
  { id: 3, name: 'Accessories', icon: '🎧' },
  { id: 4, name: 'Wearables', icon: '⌚' },
  { id: 5, name: 'Photography', icon: '📷' },
  { id: 6, name: 'Gaming', icon: '🎮' },
]
